// Auto-generated by: npm run gen:types
// Represents the complete Supabase database schema for UFO LABZ

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type OrderStatus =
  | 'pending' | 'payment_pending' | 'confirmed' | 'processing'
  | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled'
  | 'refunded' | 'partially_refunded'

export type SubscriptionStatus = 'active' | 'paused' | 'cancelled' | 'past_due' | 'trialing' | 'expired'
export type SubscriptionInterval = 'monthly' | 'bimonthly' | 'quarterly' | 'biannual' | 'annual'
export type AffiliateStatus = 'pending' | 'approved' | 'suspended' | 'rejected'
export type CommissionStatus = 'pending' | 'approved' | 'paid' | 'cancelled'
export type PayoutStatus = 'pending' | 'processing' | 'paid' | 'failed'
export type CouponType = 'percentage' | 'fixed' | 'free_shipping' | 'buy_x_get_y'
export type CouponAppliesTo = 'all' | 'products' | 'categories' | 'variants'
export type LoyaltyEvent = 'purchase' | 'review' | 'referral' | 'birthday' | 'signup' | 'social_share' | 'redemption' | 'adjustment'
export type PosPaymentMethod = 'cash' | 'card' | 'upi' | 'gift_card' | 'mixed'
export type UserRole = 'customer' | 'affiliate' | 'pos_operator' | 'admin' | 'super_admin'
export type ReviewStatus = 'pending' | 'approved' | 'rejected' | 'flagged'
export type ProductStatus = 'draft' | 'active' | 'archived'
export type VariantStatus = 'active' | 'out_of_stock' | 'discontinued'
export type GiftCardStatus = 'active' | 'redeemed' | 'expired' | 'cancelled'
export type BlogStatus = 'draft' | 'published' | 'archived'

export type LocalizedText = Record<string, string>   // { en: '...', hi: '...' }
export type LocalizedContent = Record<string, string>

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          phone: string | null
          avatar_url: string | null
          date_of_birth: string | null
          gender: string | null
          role: UserRole
          stripe_customer_id: string | null
          preferred_locale: string
          newsletter_opt_in: boolean
          sms_opt_in: boolean
          marketing_opt_in: boolean
          notes: string | null
          total_orders: number
          total_spent: number
          last_order_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'total_orders' | 'total_spent' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      addresses: {
        Row: {
          id: string
          profile_id: string
          label: string | null
          full_name: string
          phone: string | null
          line1: string
          line2: string | null
          city: string
          state: string
          postal_code: string
          country: string
          is_default: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['addresses']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['addresses']['Insert']>
      }
      products: {
        Row: {
          id: string
          name: LocalizedText
          slug: string
          tagline: LocalizedText
          description: LocalizedText
          short_description: LocalizedText
          category_id: string | null
          status: ProductStatus
          featured: boolean
          is_new: boolean
          is_best_seller: boolean
          product_color: string | null
          color_name: string | null
          sort_order: number
          base_price: number
          compare_at_price: number | null
          cost_price: number | null
          tax_class: string
          hsn_code: string | null
          gst_rate: number
          seo_title: LocalizedText
          seo_description: LocalizedText
          og_image_url: string | null
          schema_markup: Json
          track_inventory: boolean
          allow_backorder: boolean
          low_stock_threshold: number
          total_reviews: number
          avg_rating: number
          total_sold: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'total_reviews' | 'avg_rating' | 'total_sold' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['products']['Insert']>
      }
      product_variants: {
        Row: {
          id: string
          product_id: string
          name: string
          sku: string
          barcode: string | null
          price: number
          compare_at_price: number | null
          cost_price: number | null
          weight_grams: number | null
          serving_size: string | null
          servings: number | null
          stock: number
          status: VariantStatus
          is_default: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['product_variants']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['product_variants']['Insert']>
      }
      orders: {
        Row: {
          id: string
          order_number: string
          profile_id: string | null
          guest_email: string | null
          status: OrderStatus
          shipping_address: Json
          billing_address: Json
          subtotal: number
          discount_amount: number
          shipping_amount: number
          tax_amount: number
          gift_card_amount: number
          loyalty_discount: number
          total: number
          stripe_payment_intent_id: string | null
          stripe_charge_id: string | null
          payment_method: string | null
          paid_at: string | null
          coupon_id: string | null
          coupon_code: string | null
          affiliate_id: string | null
          affiliate_link_id: string | null
          shipping_method: string | null
          tracking_number: string | null
          tracking_url: string | null
          shipped_at: string | null
          delivered_at: string | null
          estimated_delivery: string | null
          loyalty_points_earned: number
          loyalty_points_used: number
          customer_note: string | null
          internal_note: string | null
          subscription_id: string | null
          is_subscription_order: boolean
          currency: string
          locale: string
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'order_number' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['orders']['Insert']>
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          variant_id: string
          product_name: LocalizedText
          variant_name: string
          sku: string
          quantity: number
          unit_price: number
          discount_amount: number
          tax_amount: number
          total: number
          image_url: string | null
        }
        Insert: Omit<Database['public']['Tables']['order_items']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['order_items']['Insert']>
      }
      affiliates: {
        Row: {
          id: string
          profile_id: string
          status: AffiliateStatus
          code: string
          commission_rate: number
          commission_tier: string
          payout_method: string | null
          payout_details: Json
          min_payout_amount: number
          total_clicks: number
          total_orders: number
          total_revenue: number
          total_commission: number
          pending_commission: number
          paid_commission: number
          balance: number
          bio: string | null
          social_links: Json
          notes: string | null
          approved_at: string | null
          approved_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['affiliates']['Row'], 'id' | 'total_clicks' | 'total_orders' | 'total_revenue' | 'total_commission' | 'pending_commission' | 'paid_commission' | 'balance' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['affiliates']['Insert']>
      }
      coupons: {
        Row: {
          id: string
          code: string
          type: CouponType
          value: number
          applies_to: CouponAppliesTo
          applies_to_ids: string[]
          min_order_amount: number | null
          max_uses: number | null
          max_uses_per_user: number
          uses_count: number
          is_active: boolean
          affiliate_id: string | null
          starts_at: string | null
          expires_at: string | null
          description: string | null
          created_by: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['coupons']['Row'], 'id' | 'uses_count' | 'created_at'>
        Update: Partial<Database['public']['Tables']['coupons']['Insert']>
      }
      subscriptions: {
        Row: {
          id: string
          profile_id: string
          plan_id: string
          status: SubscriptionStatus
          stripe_subscription_id: string | null
          shipping_address_id: string | null
          coupon_id: string | null
          subtotal: number
          discount_amount: number
          total: number
          current_period_start: string | null
          current_period_end: string | null
          next_billing_date: string | null
          cancelled_at: string | null
          pause_until: string | null
          skip_next: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['subscriptions']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['subscriptions']['Insert']>
      }
      reviews: {
        Row: {
          id: string
          product_id: string
          profile_id: string | null
          order_id: string | null
          author_name: string
          author_email: string | null
          rating: number
          title: string | null
          body: string | null
          status: ReviewStatus
          verified_purchase: boolean
          helpful_votes: number
          not_helpful_votes: number
          admin_reply: string | null
          admin_replied_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['reviews']['Row'], 'id' | 'helpful_votes' | 'not_helpful_votes' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['reviews']['Insert']>
      }
    }
    Functions: {
      is_admin: { Args: Record<never, never>; Returns: boolean }
      is_pos_operator: { Args: Record<never, never>; Returns: boolean }
      is_affiliate: { Args: Record<never, never>; Returns: boolean }
      track_affiliate_click: { Args: { p_slug: string }; Returns: void }
    }
  }
}
